name: Docker Image CI

on:
  schedule:
    - cron: 0 0 * * 3
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container: neuralegion/devops
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile
            --tag 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote
            --tag neuralegion/firefox-headless-remote
      - name: Login into Docker
        run: docker login --username=anatol1988 --password=${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: docker push neuralegion/firefox-headless-remote
      - name: Push Docker image to AWS ECR
        run: docker push 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote
