name: Docker Image CI

on:
  schedule:
    - cron: 0 0 * * 3
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to ECR
        shell: bash
        run: $(aws ecr get-login --no-include-email)
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote

      - name: Push Docker image
        run: docker push 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote
