name: Docker Image CI

on:
  schedule:
    - cron: 0 0 * * 3
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: neuralegion/devops
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Build Docker image
        run: docker build . --file Dockerfile 
            --tag 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote
            --tag neuralegion/firefox-headless-remote
      - name: Login into Docker
        run: docker login --username=anatol1988 --password=${{ secrets.DOCKER_TOKEN }}
      - name: Login in ECR
        run: eval $(aws ecr get-login --no-include-email)
      - name: Push Docker image to Docker Hub
        run: docker push neuralegion/firefox-headless-remote
      - name: Push Docker image to AWS ECR
        run: docker push 454884832027.dkr.ecr.us-east-1.amazonaws.com/firefox-headless-remote
